name: Run Python script

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run Python script
        run: |
          nohup python main.py --token=${{ secrets.staging_token }} < /dev/null & > /dev/null &
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Test this PR here (will be active for 6 hours or until a new PR is opened): https://discord.com/channels/879548962464493619/1057682935832129626
